### ISSUE TITLE
Render Color Selector Ellipse During Movement 

### ISSUE THREAD

**Issue by ealexjordan** [ealexjordan/HueView#7]
Render the ellipses while they are moving so it isn't an invisible manipulation for users that renders the ellipse on ManipulationCompleted.

**Comment by ealexjordan** [comment]
This does not need to be fixed, it is working as intended in the current state. The problem is when loading the app through visual studio the manipulation event is laggy. Tried without VS debugging and works fine. Had to turn off interia mode though in Windows.UI.Xaml.Input.ManipulationModes to just TranslateX and TranslateY.

**Comment by andschwa** [comment]
:+1:
